//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Self_checkout.WpfApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int order_id { get; set; }
        public int order_product_id { get; set; }
        public Nullable<int> order_product_quantity { get; set; }
        public Nullable<decimal> order_products_price { get; set; }
        public Nullable<System.DateTime> order_time { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
